In [2]:
import numpy as np
import pandas as pd
import requests

In [3]:
url_link = 'https://pokemondb.net/pokedex/all'
r = requests.get(url_link,headers ={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'})
read_html_pandas_data = pd.read_html(r.text)[0]
df= pd.DataFrame(read_html_pandas_data)
df.head()

,#,Name,Type,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,1,Bulbasaur,Grass Poison,318,45,49,49,65,65,45
1,2,Ivysaur,Grass Poison,405,60,62,63,80,80,60
2,3,Venusaur,Grass Poison,525,80,82,83,100,100,80
3,3,Venusaur Mega Venusaur,Grass Poison,625,80,100,123,122,120,80
4,4,Charmander,Fire,309,39,52,43,60,50,65

In [4]:
df.shape

(1075, 10)

In [5]:
df.to_csv('pokeman.csv',index=False)

In [6]:
df.to_excel('pokeman.xlsx',sheet_name='pokedex',index=False)

In [9]:
df['Type'].unique()

array(['Grass Poison', 'Fire', 'Fire Flying', 'Fire Dragon', 'Water',
       'Bug', 'Bug Flying', 'Bug Poison', 'Normal Flying', 'Normal',
       'Dark Normal', 'Poison', 'Electric', 'Electric Psychic', 'Ground',
       'Ice Steel', 'Poison Ground', 'Fairy', 'Ice', 'Ice Fairy',
       'Normal Fairy', 'Poison Flying', 'Bug Grass', 'Ground Steel',
       'Dark', 'Steel', 'Fighting', 'Fire Rock', 'Water Fighting',
       'Psychic', 'Water Poison', 'Rock Ground', 'Rock Electric',
       'Psychic Fairy', 'Water Psychic', 'Poison Psychic',
       'Electric Steel', 'Water Ice', 'Poison Dark', 'Ghost Poison',
       'Electric Grass', 'Grass Psychic', 'Grass Dragon', 'Fire Ghost',
       'Poison Fairy', 'Ground Rock', 'Grass', 'Ice Psychic',
       'Water Flying', 'Water Dark', 'Rock Water', 'Rock Flying',
       'Ice Flying', 'Psychic Flying', 'Electric Flying',
       'Fighting Flying', 'Dark Flying', 'Dragon', 'Dragon Flying',
       'Psychic Fighting', 'Water Electric', 'Fairy Flying',
       'Electric Dragon', 'Water Fairy', 'Rock', 'Grass Flying',
       'Water Ground', 'Ghost', 'Normal Psychic', 'Bug Steel',
       'Ground Flying', 'Steel Ground', 'Dark Poison', 'Bug Rock',
       'Bug Fighting', 'Dark Ice', 'Poison Fighting', 'Ice Ground',
       'Water Rock', 'Steel Flying', 'Dark Fire', 'Water Dragon',
       'Rock Dark', 'Psychic Grass', 'Fire Fighting', 'Water Grass',
       'Grass Dark', 'Bug Water', 'Grass Fighting', 'Bug Ground',
       'Bug Ghost', 'Dark Ghost', 'Steel Fairy', 'Steel Rock',
       'Fighting Psychic', 'Fire Ground', 'Ground Dragon', 'Dragon Fairy',
       'Rock Psychic', 'Ground Psychic', 'Rock Grass', 'Rock Bug',
       'Ice Water', 'Steel Psychic', 'Dragon Psychic', 'Ground Fire',
       'Grass Ground', 'Water Steel', 'Normal Water', 'Rock Steel',
       'Ghost Flying', 'Normal Fighting', 'Ghost Dark', 'Dragon Ground',
       'Fighting Steel', 'Poison Bug', 'Grass Ice', 'Ice Ghost',
       'Electric Ghost', 'Electric Fire', 'Electric Water',
       'Electric Ice', 'Steel Dragon', 'Fire Steel', 'Ghost Dragon',
       'Psychic Fire', 'Grass Fairy', 'Ground Dark', 'Fire Psychic',
       'Ice Fire', 'Dark Fighting', 'Ground Ghost', 'Normal Ghost',
       'Normal Grass', 'Water Ghost', 'Bug Electric', 'Grass Steel',
       'Ghost Fire', 'Ground Electric', 'Dark Steel', 'Dark Dragon',
       'Bug Fire', 'Steel Fighting', 'Rock Fighting', 'Flying',
       'Dragon Fire', 'Dragon Electric', 'Dragon Ice', 'Normal Ground',
       'Fire Normal', 'Fighting Dark', 'Steel Ghost', 'Dark Psychic',
       'Poison Water', 'Poison Dragon', 'Electric Normal', 'Rock Dragon',
       'Rock Ice', 'Electric Fairy', 'Rock Fairy', 'Dragon Steel',
       'Ghost Grass', 'Ice Rock', 'Flying Dragon', 'Psychic Ghost',
       'Psychic Dark', 'Fire Water', 'Grass Ghost', 'Fire Dark',
       'Fighting Ice', 'Bug Fairy', 'Water Bug', 'Poison Fire',
       'Ghost Ground', 'Ghost Fairy', 'Normal Dragon', 'Dragon Fighting',
       'Psychic Steel', 'Rock Poison', 'Psychic Dragon', 'Fighting Ghost',
       'Flying Steel', 'Bug Psychic', 'Rock Fire', 'Flying Water',
       'Electric Poison', 'Fire Bug', 'Dark Fairy', 'Ice Bug',
       'Psychic Normal', 'Electric Dark', 'Dragon Ghost', 'Fairy Steel',
       'Fighting Water', 'Dark Grass', 'Psychic Ice', 'Ground Normal'],
      dtype=object)

In [10]:
with pd.ExcelWriter('pokemantype.xlsx',engine ='xlsxwriter') as writer:
    df[df['Type']=='Dark Ice'].to_excel(writer,sheet_name='DarkIce',index=False,engine= 'xlsxwriter')
    df[df['Type']=='Bug Water'].to_excel(writer,sheet_name='BugWater',index=False,engine= 'xlsxwriter')
    df[df['Type']=='Steel Ground'].to_excel(writer,sheet_name='SteelGround',index=False,engine= 'xlsxwriter')
    df[df['Type']=='Fire Fighting'].to_excel(writer,sheet_name='FireFighting',index=False,engine= 'xlsxwriter')

In [11]:
df2 = pd.read_csv('RealGDP31102022.csv')
df2.head()

,tyear,Period,Agriculture,CropProduction,Livestock,Forestry,Fishing,Industry,MiningAndQuarrying,CrudePetroleumAndNaturalGas,...,RealEstate,ProfessionalScientificAndTechnicalServices,AdministrativeAndSupportServicesBusinessServices,PublicAdministration,Education,HumanHealthAndSocialServices,OtherServices,GDP at 2010 Constant Basic Prices,NetTaxesOnProducts,GDP at 2010 Constant Market Prices
1981,Annual,2364.37,1854.76,341.41,77.90,90.30,11753.40,5044.55,4977.42,21.33,...,421.38,3.23,807.08,242.56,113.46,133.53,19549.56,198.97,19748.53,NaN
1982,Annual,2425.96,1897.08,361.12,73.91,93.86,10189.10,4507.93,4453.09,10.29,...,423.67,3.25,825.92,248.22,117.88,134.60,18219.27,185.70,18404.96,NaN
1983,Annual,2409.08,1842.70,393.13,75.28,97.96,8255.76,4096.99,4052.98,9.73,...,481.17,3.69,844.77,253.88,118.27,126.60,16228.81,165.58,16394.39,NaN
1984,Annual,2303.51,1759.12,399.69,76.69,68.01,8392.25,4602.27,4559.20,14.03,...,518.36,3.98,863.61,259.55,117.82,103.73,16048.31,163.18,16211.49,NaN
1985,Annual,2731.06,2180.91,428.10,78.08,43.97,8768.30,4962.81,4918.27,26.19,...,602.46,4.62,882.46,265.21,120.43,99.41,16997.52,172.56,17170.08,NaN

In [12]:
df2.reset_index(inplace=True)
df2.head()

,index,tyear,Period,Agriculture,CropProduction,Livestock,Forestry,Fishing,Industry,MiningAndQuarrying,...,RealEstate,ProfessionalScientificAndTechnicalServices,AdministrativeAndSupportServicesBusinessServices,PublicAdministration,Education,HumanHealthAndSocialServices,OtherServices,GDP at 2010 Constant Basic Prices,NetTaxesOnProducts,GDP at 2010 Constant Market Prices
0,1981,Annual,2364.37,1854.76,341.41,77.90,90.30,11753.40,5044.55,4977.42,...,421.38,3.23,807.08,242.56,113.46,133.53,19549.56,198.97,19748.53,NaN
1,1982,Annual,2425.96,1897.08,361.12,73.91,93.86,10189.10,4507.93,4453.09,...,423.67,3.25,825.92,248.22,117.88,134.60,18219.27,185.70,18404.96,NaN
2,1983,Annual,2409.08,1842.70,393.13,75.28,97.96,8255.76,4096.99,4052.98,...,481.17,3.69,844.77,253.88,118.27,126.60,16228.81,165.58,16394.39,NaN
3,1984,Annual,2303.51,1759.12,399.69,76.69,68.01,8392.25,4602.27,4559.20,...,518.36,3.98,863.61,259.55,117.82,103.73,16048.31,163.18,16211.49,NaN
4,1985,Annual,2731.06,2180.91,428.10,78.08,43.97,8768.30,4962.81,4918.27,...,602.46,4.62,882.46,265.21,120.43,99.41,16997.52,172.56,17170.08,NaN

In [13]:
df2.columns

Index(['index', 'tyear', 'Period', 'Agriculture', 'CropProduction',
       'Livestock', 'Forestry', 'Fishing', 'Industry', 'MiningAndQuarrying',
       'CrudePetroleumAndNaturalGas', 'CoalMining', 'MetalOres',
       'QuarryingAndOtherMinerals', 'Manufacturing', 'OilRefining', 'Cement',
       'FoodBeverageAndTobacco', 'TextileApparelAndFootwear',
       'WoodAndWoodProducts', 'PulpPaperAndPaperProducts',
       'ChemicalAndPharmaceuticalProducts', 'NonMetallicProducts',
       'PlasticAndRubberProducts', 'ElectricalAndElectronics',
       'BasicMetalIronAndSteel', 'MotorVehiclesAndAssembly',
       'OtherManufacturing', 'ElectricityGasSteamAndAirCon',
       'WaterSupplySewageWaste', 'Construction', 'Services', 'Trade',
       'AccommodationAndFoodServices', 'TransportationAndStorage',
       'RoadTransport', 'RailTransportAndPipelines', 'WaterTransport',
       'AirTransport', 'TransportServices', 'PostAndCourierServices',
       'InformationAndCommunication', 'Publishing',
       'MotionPicturesSoundRecordingAndMusicProduction', 'Broadcasting',
       'ArtsEntertainmentAndRecreation', 'FinanceAndInsurance',
       'FinancialInstitutions', 'Insurance', 'RealEstate',
       'ProfessionalScientificAndTechnicalServices',
       'AdministrativeAndSupportServicesBusinessServices',
       'PublicAdministration', 'Education', 'HumanHealthAndSocialServices',
       'OtherServices', 'GDP at 2010 Constant Basic Prices',
       'NetTaxesOnProducts', 'GDP at 2010 Constant Market Prices'],
      dtype='object')

In [14]:
df2.rename({'index':'Year', 'tyear':'Period', 'Period':'Agriculture', 'Agriculture':'CropProduction', 'CropProduction':'Livestock',
'Livestock':'Forestry', 'Forestry':'Fishing', 'Fishing':'Industry', 'Industry':'MiningAndQuarrying','MiningAndQuarrying':'CrudeOil',
'CrudePetroleumAndNaturalGas':'CoalMining', 'CoalMining':'Metalores', 'MetalOres':'OtherMinerals',
'QuarryingAndOtherMinerals':'Manufacturing', 'Manufacturing':'OilRefining', 'OilRefining':'Cement', 'Cement':'FoodBeverageAndTobacco',
'FoodBeverageAndTobacco':'TextileApparelAndFootwear', 'TextileApparelAndFootwear':'WoodAndWoodProducts',
'WoodAndWoodProducts':'PulpPaperAndPaperProducts', 'PulpPaperAndPaperProducts':'ChemicalAndPharmaceuticalProducts',
'ChemicalAndPharmaceuticalProducts':'NonMetallicProducts', 'NonMetallicProducts':'PlasticAndRubberProducts',
'PlasticAndRubberProducts':'ElectricalAndElectronics', 'ElectricalAndElectronics':'BasicMetalIronAndSteel',
'BasicMetalIronAndSteel':'MotorVehiclesAndAssembly', 'MotorVehiclesAndAssembly':'OtherManufacturing',
'OtherManufacturing':'ElectricityGasSteamAndAirCon', 'ElectricityGasSteamAndAirCon':'WaterSupplySewageWaste',
'WaterSupplySewageWaste':'Construction', 'Construction':'Services', 'Services':'Trade', 'Trade':'AccommodationAndFoodServices',
'AccommodationAndFoodServices':'TransportationAndStorage', 'TransportationAndStorage':'RoadTransport',
'RoadTransport':'RailTransportAndPipelines', 'RailTransportAndPipelines':'WaterTransport', 'WaterTransport':'AirTransport',
'AirTransport':'TransportServices', 'TransportServices':'PostAndCourierServices', 'PostAndCourierServices':'InformationAndCommunication',
'InformationAndCommunication':'Publishing', 'Publishing':'MotionPicturesSoundRecordingAndMusicProduction',
'MotionPicturesSoundRecordingAndMusicProduction':'Broadcasting', 'Broadcasting':'ArtsEntertainmentAndRecreation',
'ArtsEntertainmentAndRecreation':'FinanceAndInsurance', 'FinanceAndInsurance':'FinancialInstitutions',
'FinancialInstitutions':'Insurance', 'Insurance':'RealEstate', 'RealEstate':'ProfessionalScientificAndTechnicalServices',
'ProfessionalScientificAndTechnicalServices':'AdministrativeAndSupportServicesBusinessServices',
'AdministrativeAndSupportServicesBusinessServices':'PublicAdministration',
'PublicAdministration':'Education', 'Education':'HumanHealthAndSocialServices', 'HumanHealthAndSocialServices':'OtherServices','OtherServices':'GDP at 2010 Constant Basic Prices', 'GDP at 2010 Constant Basic Prices':'NetTaxesOnProducts','NetTaxesOnProducts':'GDP at 2010 Constant Market Prices', 'GDP at 2010 Constant Market Prices':'UNKNOWN'},axis = 1,inplace=True)
df2.head()

,Year,Period,Agriculture,CropProduction,Livestock,Forestry,Fishing,Industry,MiningAndQuarrying,CrudeOil,...,ProfessionalScientificAndTechnicalServices,AdministrativeAndSupportServicesBusinessServices,PublicAdministration,Education,HumanHealthAndSocialServices,OtherServices,GDP at 2010 Constant Basic Prices,NetTaxesOnProducts,GDP at 2010 Constant Market Prices,UNKNOWN
0,1981,Annual,2364.37,1854.76,341.41,77.90,90.30,11753.40,5044.55,4977.42,...,421.38,3.23,807.08,242.56,113.46,133.53,19549.56,198.97,19748.53,NaN
1,1982,Annual,2425.96,1897.08,361.12,73.91,93.86,10189.10,4507.93,4453.09,...,423.67,3.25,825.92,248.22,117.88,134.60,18219.27,185.70,18404.96,NaN
2,1983,Annual,2409.08,1842.70,393.13,75.28,97.96,8255.76,4096.99,4052.98,...,481.17,3.69,844.77,253.88,118.27,126.60,16228.81,165.58,16394.39,NaN
3,1984,Annual,2303.51,1759.12,399.69,76.69,68.01,8392.25,4602.27,4559.20,...,518.36,3.98,863.61,259.55,117.82,103.73,16048.31,163.18,16211.49,NaN
4,1985,Annual,2731.06,2180.91,428.10,78.08,43.97,8768.30,4962.81,4918.27,...,602.46,4.62,882.46,265.21,120.43,99.41,16997.52,172.56,17170.08,NaN

In [15]:
df2.isnull().sum()

Year                                                 0
Period                                               0
Agriculture                                          0
CropProduction                                       0
Livestock                                            0
Forestry                                             0
Fishing                                              0
Industry                                             0
MiningAndQuarrying                                   0
CrudeOil                                             0
CoalMining                                           0
Metalores                                            0
OtherMinerals                                        0
Manufacturing                                        0
OilRefining                                          0
Cement                                               0
FoodBeverageAndTobacco                               0
TextileApparelAndFootwear                            0
WoodAndWoodProducts                                  0
PulpPaperAndPaperProducts                            0
ChemicalAndPharmaceuticalProducts                    0
NonMetallicProducts                                  0
PlasticAndRubberProducts                             0
ElectricalAndElectronics                             0
BasicMetalIronAndSteel                               0
MotorVehiclesAndAssembly                             0
OtherManufacturing                                   0
ElectricityGasSteamAndAirCon                         0
WaterSupplySewageWaste                               0
Construction                                         0
Services                                             0
Trade                                                0
AccommodationAndFoodServices                         0
TransportationAndStorage                             0
RoadTransport                                        0
RailTransportAndPipelines                            0
WaterTransport                                       0
AirTransport                                         0
TransportServices                                    0
PostAndCourierServices                               0
InformationAndCommunication                          0
Publishing                                           0
MotionPicturesSoundRecordingAndMusicProduction       0
Broadcasting                                         0
ArtsEntertainmentAndRecreation                       0
FinanceAndInsurance                                  0
FinancialInstitutions                                0
Insurance                                            0
RealEstate                                           0
ProfessionalScientificAndTechnicalServices           0
AdministrativeAndSupportServicesBusinessServices     0
PublicAdministration                                 0
Education                                            0
HumanHealthAndSocialServices                         0
OtherServices                                        0
GDP at 2010 Constant Basic Prices                    0
NetTaxesOnProducts                                   0
GDP at 2010 Constant Market Prices                   0
UNKNOWN                                             85
dtype: int64

In [16]:
df2.drop('UNKNOWN',axis=1,inplace=True)

In [18]:
df2['Period'].unique()

array(['Annual', 'Q1', 'Q2', 'Q3', 'Q4'], dtype=object)

In [20]:
df3 = df2[df2['Period'] == 'Annual']
df3

,Year,Period,Agriculture,CropProduction,Livestock,Forestry,Fishing,Industry,MiningAndQuarrying,CrudeOil,...,RealEstate,ProfessionalScientificAndTechnicalServices,AdministrativeAndSupportServicesBusinessServices,PublicAdministration,Education,HumanHealthAndSocialServices,OtherServices,GDP at 2010 Constant Basic Prices,NetTaxesOnProducts,GDP at 2010 Constant Market Prices
0,1981,Annual,2364.37,1854.76,341.41,77.90,90.30,11753.40,5044.55,4977.42,...,1063.96,421.38,3.23,807.08,242.56,113.46,133.53,19549.56,198.97,19748.53
1,1982,Annual,2425.96,1897.08,361.12,73.91,93.86,10189.10,4507.93,4453.09,...,1074.05,423.67,3.25,825.92,248.22,117.88,134.60,18219.27,185.70,18404.96
2,1983,Annual,2409.08,1842.70,393.13,75.28,97.96,8255.76,4096.99,4052.98,...,1086.70,481.17,3.69,844.77,253.88,118.27,126.60,16228.81,165.58,16394.39
3,1984,Annual,2303.51,1759.12,399.69,76.69,68.01,8392.25,4602.27,4559.20,...,1086.93,518.36,3.98,863.61,259.55,117.82,103.73,16048.31,163.18,16211.49
4,1985,Annual,2731.06,2180.91,428.10,78.08,43.97,8768.30,4962.81,4918.27,...,1091.38,602.46,4.62,882.46,265.21,120.43,99.41,16997.52,172.56,17170.08
5,1986,Annual,2986.84,2427.10,421.63,86.59,51.51,8347.53,4860.75,4825.50,...,1100.91,650.81,5.00,901.31,270.88,122.56,103.45,17007.77,172.77,17180.55
6,1987,Annual,2891.67,2330.00,433.43,87.59,40.65,8799.38,4737.23,4704.42,...,1112.49,658.62,5.06,920.15,276.54,124.41,104.49,17552.10,178.24,17730.34
7,1988,Annual,3174.57,2581.60,444.27,88.91,59.79,9514.81,4856.73,4828.68,...,1123.08,665.20,5.11,939.00,282.20,125.13,105.52,18839.55,191.14,19030.69
8,1989,Annual,3325.95,2710.67,453.16,67.31,94.81,9442.83,5435.67,5407.01,...,1139.87,675.18,5.18,957.84,287.87,125.83,107.09,19201.16,194.80,19395.96
9,1990,Annual,3464.72,2828.59,462.22,72.61,101.29,11148.10,6860.85,6831.77,...,1196.55,688.69,5.29,976.69,293.53,127.10,109.23,21462.73,217.47,21680.20
10,1991,Annual,3590.84,2955.88,454.82,74.79,105.35,10910.56,6265.30,6224.45,...,1244.15,699.01,5.37,987.04,296.64,129.95,110.87,21539.61,218.28,21757.90
11,1992,Annual,3674.79,3044.55,458.92,76.51,94.81,11578.98,6411.86,6381.26,...,1292.35,719.98,5.53,1015.43,305.17,137.58,118.30,22537.10,228.45,22765.55
12,1993,Annual,3743.67,3132.84,461.67,78.04,71.11,10790.31,6415.38,6394.60,...,1346.31,748.79,5.75,1044.82,314.01,140.62,130.13,22078.07,224.17,22302.24
13,1994,Annual,3839.68,3226.83,466.29,80.07,66.49,10151.70,6246.67,6229.46,...,1386.53,774.99,5.95,1059.74,318.49,140.26,147.96,21676.85,220.62,21897.47
14,1995,Annual,3977.38,3336.54,485.87,81.83,73.14,9845.97,6393.05,6375.97,...,1430.72,803.66,6.17,1059.12,318.30,138.09,171.63,21660.49,221.07,21881.56
15,1996,Annual,4133.55,3463.00,499.96,82.24,88.35,10402.19,6850.37,6832.84,...,1445.02,832.58,6.39,1089.77,327.52,141.10,197.38,22568.87,230.83,22799.69
16,1997,Annual,4305.68,3611.91,512.46,82.98,98.33,10599.70,6952.09,6933.58,...,1536.91,861.73,6.62,1108.61,333.18,143.41,226.99,23231.12,238.22,23469.34
17,1998,Annual,4475.24,3752.77,526.30,83.98,112.20,10641.26,7103.38,7083.99,...,1628.65,904.81,6.95,1127.46,338.84,147.50,272.38,23829.76,245.39,24075.15
18,1999,Annual,4703.64,3949.42,541.03,85.07,128.12,10201.81,6572.89,6552.69,...,1690.33,944.63,7.25,1146.31,344.51,150.27,326.86,23967.59,248.18,24215.78
19,2000,Annual,4840.97,4067.90,553.48,86.35,133.25,10962.84,7302.99,7281.94,...,1756.08,985.26,7.56,1165.15,350.17,157.23,353.01,25169.54,260.88,25430.42
20,2001,Annual,5024.54,4222.48,570.08,88.07,143.91,11576.32,7685.37,7662.98,...,1843.82,1034.52,7.94,1184.00,355.83,160.23,388.31,26658.62,276.69,26935.32
21,2002,Annual,7817.08,6977.88,597.50,88.69,153.02,11725.42,7247.86,7225.68,...,1899.13,1101.59,8.46,1398.33,383.83,163.35,446.70,30745.19,319.08,31064.27
22,2003,Annual,8364.83,7493.02,622.56,90.02,159.23,13151.23,8975.81,8952.62,...,1956.11,1150.02,8.83,1398.33,410.83,166.43,452.55,33004.80,341.83,33346.62
23,2004,Annual,8888.57,7956.66,663.03,95.87,173.02,13382.86,9275.14,9248.05,...,2168.33,1189.54,9.13,1550.04,455.40,184.49,501.65,36057.74,373.64,36431.37
24,2005,Annual,9516.99,8524.15,707.87,101.55,183.43,13609.76,9323.75,9294.05,...,2408.82,1252.58,9.62,1612.04,503.44,203.06,554.32,38378.80,398.22,38777.01
25,2006,Annual,10222.47,9162.65,756.73,107.66,195.43,13342.47,8907.47,8874.70,...,2690.07,1336.33,10.26,1683.80,557.67,224.14,613.14,40703.68,423.00,41126.68
26,2007,Annual,10958.47,9826.77,809.16,114.25,208.29,13085.27,8508.82,8471.95,...,3005.42,1425.80,10.95,1758.82,617.78,247.44,678.27,43385.88,451.51,43837.39
27,2008,Annual,11645.37,10437.99,864.19,121.22,221.97,12817.79,7989.19,7947.72,...,3359.76,1521.04,11.68,1836.91,684.31,273.16,750.84,46320.01,482.75,46802.76
28,2009,Annual,12330.33,11046.16,920.20,128.31,235.66,13138.95,8030.01,7983.63,...,3727.34,1615.16,12.40,1918.00,752.79,300.74,825.12,50042.36,521.90,50564.26
33,2010,Annual,13048.89,11683.90,979.56,135.72,249.71,13826.43,8454.55,8402.68,...,4127.99,1711.70,13.14,1998.47,826.67,330.96,900.02,54612.26,857.09,55469.35
38,2011,Annual,13429.38,12017.19,999.40,142.46,270.32,14986.62,8658.05,8598.64,...,4145.87,2031.47,13.82,2307.38,1087.67,374.12,934.60,57511.04,669.31,58180.35
43,2012,Annual,14329.71,12919.54,972.76,146.09,291.31,15350.45,8244.39,8173.26,...,4379.94,2190.07,13.37,1838.73,1105.90,390.30,1401.47,59929.89,740.16,60670.05
48,2013,Annual,14750.52,13247.80,1030.94,154.31,317.47,15682.46,7188.15,7105.28,...,4904.64,2265.11,13.72,1828.84,1278.41,427.72,1551.53,63218.72,724.12,63942.85
53,2014,Annual,15380.39,13793.45,1086.85,161.34,338.75,16742.15,7107.03,7011.81,...,5155.73,2390.44,13.98,1874.94,1391.95,472.63,1825.45,67152.79,824.67,67977.46
58,2015,Annual,15952.22,14274.94,1151.32,167.26,358.70,16366.66,6732.51,6629.96,...,5264.70,2516.07,14.47,1644.78,1498.71,484.34,2151.38,69023.93,756.76,69780.69
63,2016,Annual,16607.34,14894.45,1185.12,171.64,356.13,14918.15,5759.82,5672.21,...,4903.60,2536.29,14.37,1569.52,1518.93,475.69,2257.47,67931.24,721.19,68652.43
68,2017,Annual,17179.50,15437.05,1204.21,177.33,360.91,15238.28,6025.78,5938.05,...,4694.39,2529.68,14.47,1563.62,1507.98,474.24,2310.55,68490.98,714.71,69205.69
73,2018,Annual,17544.15,15786.44,1208.13,182.75,366.83,15523.43,6092.48,5995.88,...,4471.86,2544.14,14.44,1531.58,1507.56,472.70,2360.64,69799.94,736.41,70536.35
78,2019,Annual,17958.58,16181.99,1210.06,187.47,379.06,15882.35,6362.63,6270.86,...,4366.35,2547.30,14.72,1470.22,1519.66,474.17,2405.54,71387.83,706.27,72094.09
83,2020,Annual,18348.18,16544.52,1233.11,190.51,380.03,14953.72,5819.39,5713.20,...,3963.59,2345.58,14.32,1471.66,1313.39,484.74,2266.54,70014.37,786.17,70800.54

In [21]:
df3.to_csv('REALGDP.csv',index=False)